# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 15:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='\u4fe1\u606f\u5185\u5bb9')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
                ('send_from', models.ManyToManyField(related_name='send_from_user', to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u9001\u8005')),
                ('send_to', models.ManyToManyField(related_name='send_to_user', to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u9001\u7ed9\u8c01')),
            ],
        ),
    ]
