# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statistics', '0012_auto_20170711_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlReviewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_what', models.CharField(max_length=255, verbose_name='\u6267\u884csql\u7684\u76ee\u7684\u662f')),
                ('submit_time', models.DateTimeField(auto_now=True, verbose_name='\u63d0\u4ea4\u8bf7\u6c42\u7684\u65f6\u95f4')),
                ('execute_time', models.DateTimeField(verbose_name='\u8981\u6c42\u6267\u884c\u7684\u65f6\u95f4')),
                ('sql', models.TextField(verbose_name='\u60f3\u8981\u6267\u884c\u7684SQL')),
                ('is_checked', models.BooleanField(verbose_name='\u662f\u5426\u901a\u8fc7\u4ee3\u7801\u5ba1\u6838')),
                ('is_reviewed', models.BooleanField(verbose_name='\u662f\u5426\u9879\u76ee\u7ecf\u7406\u5ba1\u6838')),
                ('is_executed', models.BooleanField(verbose_name='\u662f\u5426\u6267\u884c')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.MysqlInstance', verbose_name='\u5bf9\u5e94\u7ec4\u5185\u7684\u5177\u4f53\u5b9e\u4f8b')),
                ('instance_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.MysqlInstanceGroup', verbose_name='\u5b9e\u4f8b\u7ec4')),
            ],
            options={
                'verbose_name': 'SQL\u5ba1\u6838\u63d0\u4ea4\u8bb0\u5f55',
                'verbose_name_plural': 'SQL\u5ba1\u6838\u63d0\u4ea4\u8bb0\u5f55',
            },
        ),
    ]
