# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlreviewrecord',
            name='user_name',
            field=models.CharField(default='system', max_length=30, verbose_name='\u7533\u8bf7\u4eba'),
        ),
    ]
