# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_review', '0002_auto_20170716_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlreviewrecord',
            name='for_what',
            field=models.CharField(max_length=255, verbose_name='\u6267\u884csql\u7684\u76ee\u7684'),
        ),
        migrations.AlterField(
            model_name='sqlreviewrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u81ea\u589eID'),
        ),
    ]
