# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_review', '0003_auto_20170717_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlreviewrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
