# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_review', '0004_auto_20170717_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlExecuteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_record_id', models.IntegerField(default=0, verbose_name='\u5bf9\u5e94\u5ba1\u6838\u8bb0\u5f55\u7684id')),
                ('sequence', models.CharField(default='', max_length=30, verbose_name='\u6267\u884c\u7ed3\u679c\u4e2d\u7684sequence\uff0c\u7528\u6765\u67e5\u627e\u591a\u7528\u7684\u56de\u6eda\u8bed\u53e5')),
                ('sql', models.TextField(verbose_name='\u6267\u884c\u7684sql')),
                ('backup_db_name', models.CharField(default='', max_length=40, verbose_name='\u5907\u4efd\u6570\u636e\u5e93\u540d')),
                ('sql_sha1', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u5982\u679c\u662fosc\uff0c\u4f1a\u6709\u6b64\u503c')),
            ],
        ),
    ]
