# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_review', '0005_sqlexecuterecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SqlExecuteRecord',
            new_name='SqlBackupRecord',
        ),
    ]
