# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_review', '0006_auto_20170730_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlbackuprecord',
            name='backup_db_name',
        ),
        migrations.RemoveField(
            model_name='sqlbackuprecord',
            name='sql',
        ),
    ]
