# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_review', '0009_sqlreviewrecord_is_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationForSql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='\u516c\u5171\u68c0\u67e5\u9879', max_length=20, verbose_name='\u89c4\u8303\u7c7b\u578b')),
                ('content', models.CharField(default='\u8bf7\u586b\u5199\u5185\u5bb9', max_length=255, verbose_name='\u89c4\u8303\u5185\u5bb9')),
            ],
        ),
    ]
