# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql_review', '0010_specificationforsql'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationContentForSql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='0', max_length=255, verbose_name='\u89c4\u8303\u5185\u5bb9')),
            ],
            options={
                'verbose_name': 'SQL\u89c4\u8303\u5185\u5bb9',
                'verbose_name_plural': 'SQL\u89c4\u8303\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='SpecificationTypeForSql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='\u516c\u5171\u68c0\u67e5\u9879', max_length=20, verbose_name='\u89c4\u8303\u7c7b\u578b')),
            ],
            options={
                'verbose_name': 'SQL\u89c4\u8303\u7c7b\u578b',
                'verbose_name_plural': 'SQL\u89c4\u8303\u7c7b\u578b',
            },
        ),
        migrations.DeleteModel(
            name='SpecificationForSql',
        ),
        migrations.AddField(
            model_name='specificationcontentforsql',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql_review.SpecificationTypeForSql'),
        ),
    ]
