# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Mysql \u4e3b\u4ece\u5173\u7cfb',
                'verbose_name_plural': 'Mysql \u4e3b\u4ece\u5173\u7cfb',
            },
        ),
        migrations.CreateModel(
            name='MysqlInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5b9e\u4f8b\u540d\u79f0')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('port', models.IntegerField(default=3306, verbose_name='\u5b9e\u4f8b\u7aef\u53e3')),
                ('login_instance_account', models.CharField(default='db_platform', max_length=20, verbose_name='\u767b\u9646\u5b9e\u4f8b\u8d26\u53f7')),
                ('login_instance_password', models.CharField(max_length=20, verbose_name='\u767b\u9646\u5b9e\u4f8b\u5bc6\u7801')),
                ('x_position', models.IntegerField(default=0, verbose_name='\u62d3\u6251\u56fe\u4e2d\u7684x\u8f74')),
                ('y_position', models.IntegerField(default=0, verbose_name='\u62d3\u6251\u56fe\u4e2d\u7684y\u8f74')),
            ],
            options={
                'verbose_name': 'Mysql \u5b9e\u4f8b',
                'verbose_name_plural': 'Mysql \u5b9e\u4f8b',
            },
        ),
        migrations.CreateModel(
            name='MysqlInstanceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5b9e\u4f8b\u7ec4')),
                ('code', models.CharField(default='vo', max_length=2, verbose_name='\u7ec4\u4ee3\u53f7')),
            ],
            options={
                'verbose_name': 'Mysql \u5b9e\u4f8b\u7ec4',
                'verbose_name_plural': 'Mysql \u5b9e\u4f8b\u7ec4',
            },
        ),
        migrations.AddField(
            model_name='mysqlinstance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.MysqlInstanceGroup', verbose_name='\u5b9e\u4f8b\u7ec4\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='instancerelation',
            name='belong_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='statistics.MysqlInstanceGroup', verbose_name='Mysql \u7ec4'),
        ),
        migrations.AddField(
            model_name='instancerelation',
            name='master_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_instance_id', to='statistics.MysqlInstance', verbose_name='\u4e3bid'),
        ),
        migrations.AddField(
            model_name='instancerelation',
            name='slave_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave_instance_id', to='statistics.MysqlInstance', verbose_name='\u4eceid'),
        ),
        migrations.AlterUniqueTogether(
            name='mysqlinstance',
            unique_together=set([('ip', 'port')]),
        ),
    ]
