# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5b9e\u4f8b\u540d\u79f0')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('instance_port', models.IntegerField(default=3306, verbose_name='\u5b9e\u4f8b\u7aef\u53e3')),
                ('login_instance_account', models.CharField(default='db_platform', max_length=20,
                                                            verbose_name='\u767b\u9646\u5b9e\u4f8b\u8d26\u53f7')),
                ('login_instance_password',
                 models.CharField(max_length=20, verbose_name='\u767b\u9646\u5b9e\u4f8b\u5bc6\u7801')),
            ],
            options={
                'verbose_name': 'Mysql \u5b9e\u4f8b',
                'verbose_name_plural': 'Mysql \u5b9e\u4f8b',
            },
        ),
    ]
