# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_instance',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_instance_id',
                                   to='statistics.MysqlInstance', verbose_name='\u4e3bid')),
                ('slave_instance',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave_instance_id',
                                   to='statistics.MysqlInstance', verbose_name='\u4eceid')),
            ],
        ),
    ]
