# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('statistics', '0002_instancerelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlInstanceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5b9e\u4f8b\u7ec4')),
            ],
            options={
                'verbose_name': 'Mysql \u5b9e\u4f8b\u7ec4',
                'verbose_name_plural': 'Mysql \u5b9e\u4f8b\u7ec4',
            },
        ),
        migrations.AlterModelOptions(
            name='instancerelation',
            options={'verbose_name': 'Mysql \u4e3b\u4ece\u5173\u7cfb',
                     'verbose_name_plural': 'Mysql \u4e3b\u4ece\u5173\u7cfb'},
        ),
        migrations.AddField(
            model_name='instancerelation',
            name='belong_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='statistics.MysqlInstanceGroup', verbose_name='Mysql \u7ec4'),
        ),
    ]
