# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('statistics', '0003_auto_20170709_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancerelation',
            name='belong_group',
        ),
    ]
