# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statistics', '0006_mysqlinstance_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlinstance',
            name='x_position',
            field=models.IntegerField(default=0, verbose_name='\u62d3\u6251\u56fe\u4e2d\u7684x\u8f74'),
        ),
        migrations.AddField(
            model_name='mysqlinstance',
            name='y_position',
            field=models.IntegerField(default=0, verbose_name='\u62d3\u6251\u56fe\u4e2d\u7684y\u8f74'),
        ),
    ]
