# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statistics', '0007_auto_20170709_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlinstancegroup',
            name='code',
            field=models.CharField(default='vo', max_length=2, verbose_name='\u7ec4\u4ee3\u53f7'),
        ),
    ]
