# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statistics', '0008_mysqlinstancegroup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlinstance',
            name='comment',
            field=models.CharField(default='', max_length=50, verbose_name='\u5907\u6ce8'),
        ),
    ]
