# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('statistics', '0009_mysqlinstance_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqlinstance',
            name='comment',
        ),
    ]
